### ISSUE TITLE
Updating dependencies breaks this project

### ISSUE THREAD

**Issue by SENPAY98K** [nolddor/steam-gemify-tool#1]

**Comment by nolddor** [comment]
Hi, thanks for reaching us out.

Please, provide:

- Bug description
- Expected behavior
- Actual behavior
- Steps to reproduce
- NPM / Node.js logs while reproducing the problem

Do not forget to remove any sensitive data from logs outputs.

Thx!

**Comment by nolddor** [comment]
Hey, we haven't heard back from you since a while...

Therefore, we are going mark this issue as closed due to the lack of information to reproduce the problem.
Have a great day!
